Algoritmo "SejaBemVIndo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Lucas Moreira de Medeiros
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis
nome:caractere


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite seu nome : ")
leia (nome)
escreva("Seja bem vindo, ", nome)

Fimalgoritmo

