Algoritmo "nomeInteiro"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Lucas moreira
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis 
nome:caractere
sobrenome:caractere
nomecompleto:caractere


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("digite seu nome : ")
leia(nome)
escreva("Digite seu sobrenome : ")
leia(sobrenome)
nomecompleto <-nome+ "" + sobrenome
escreva("escreva nome completo")


Fimalgoritmo