Algoritmo "subtração"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Lucas Moreira de Medeiros
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis 
numero01:inteiro
numero02:inteiro
resultado:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("insira o primeiro numero da subtração")
leia(numero01)
escreva("insira o segundo numero da subtração")
leia(numero02)
resultado <- numero01 - numero02
escreva("a subtração de dois numeros é: ", resultado)


Fimalgoritmo