Algoritmo "Sucessor"
// Disciplina   : [Lógica de Programação com Visualg]
// Professor   : Jailson
// Descrição   : Solicita dois números para o
 //usuario, soma e exibe o resultado
// Autor(a)    : Lucas moreira de medeiros
// Data atual  : 26/03/2026
Var
// Seção de Declarações das variáveis
numero01:inteiro

resultado:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite um numero inteiro")
leia(numero01)


resultado<- numero01 + 1
escreva ("o Sucessor do numero inteiro é : ",resultado)



Fimalgoritmo